#!/usr/bin/env bash
# Mechanical drift checker for the vcfdist agent-doc topology.
# Treat markdown structure as testable: short routing files, required
# specialized files, anchor presence, no duplicated harness instruction
# files, no AI-attribution markers.
#
# Usage:
#   bash tools/check_agent_docs.sh

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

fail=0

echo "Checking AGENTS.md length..."
if [ "$(wc -l < AGENTS.md)" -gt 160 ]; then
  echo "FAIL: AGENTS.md should stay short; target <=110, hard cap 160."
  fail=1
fi

echo "Checking required agent docs..."
required_files=(
  docs/agents/index.md
  docs/agents/orchestrator.md
  docs/agents/explorer.md
  docs/agents/librarian.md
  docs/agents/oracle.md
  docs/agents/designer.md
  docs/agents/fixer.md
  docs/agents/documentarian.md
)
for p in "${required_files[@]}"; do
  if [ ! -f "$p" ]; then
    echo "FAIL: missing $p"
    fail=1
  fi
done

echo "Checking that documentarian is listed in the agent map..."
if ! grep -qE '(^|[^A-Za-z])documentarian([^A-Za-z]|$)' docs/agents/index.md; then
  echo "FAIL: docs/agents/index.md must document the documentarian agent."
  fail=1
fi

echo "Checking AGENTS.md pointers..."
grep -q 'INFRASTRUCTURE_SUMMARY.md' AGENTS.md || {
  echo "FAIL: AGENTS.md must point to INFRASTRUCTURE_SUMMARY.md"
  fail=1
}
grep -q 'docs/agents/index.md' AGENTS.md || {
  echo "FAIL: AGENTS.md must point to docs/agents/index.md"
  fail=1
}

echo "Checking CLAUDE.md pointer file..."
if [ -f CLAUDE.md ]; then
  if [ "$(wc -l < CLAUDE.md)" -gt 10 ] || ! grep -q 'AGENTS.md' CLAUDE.md; then
    echo "FAIL: CLAUDE.md must be a short pointer to AGENTS.md (<=10 lines, references AGENTS.md)."
    fail=1
  fi
fi

echo "Checking for duplicate per-harness instruction files..."
if git ls-files | grep -qE '^(COPILOT_INSTRUCTIONS|GEMINI|GEMINI_INSTRUCTIONS|SKILL|RULES|CONTEXT)\.md$'; then
  echo "FAIL: duplicate harness instruction file committed."
  git ls-files | grep -E '^(COPILOT_INSTRUCTIONS|GEMINI|GEMINI_INSTRUCTIONS|SKILL|RULES|CONTEXT)\.md$'
  fail=1
fi

echo "Checking for stale doc-reviewer naming..."
if git grep -niE 'doc-reviewer|doc reviewer' -- '*.md' ':!docs/archive/**'; then
  echo "FAIL: use documentarian, not doc-reviewer."
  fail=1
fi

echo "Checking for AI attribution markers..."
if git grep -niE '(generated by (claude|copilot|gpt|gemini|cursor)|ai[- ](authored|generated|written)|co-authored-by:.*(claude|copilot|gpt|gemini|cursor))' \
     -- ':!**/*.lock' ':!docs/dev/' ':!tools/check_agent_docs.sh'; then
  echo "FAIL: AI attribution marker found."
  fail=1
fi

echo "Checking per-agent doc H1 anchors..."
required_anchors=(
  "docs/agents/index.md:# Agent Map"
  "docs/agents/orchestrator.md:# Orchestrator"
  "docs/agents/explorer.md:# Explorer"
  "docs/agents/librarian.md:# Librarian"
  "docs/agents/oracle.md:# Oracle"
  "docs/agents/designer.md:# Designer"
  "docs/agents/fixer.md:# Fixer"
  "docs/agents/documentarian.md:# Documentarian"
)
for item in "${required_anchors[@]}"; do
  file="${item%%:*}"
  anchor="${item#*:}"
  if [ -f "$file" ] && ! grep -qF "$anchor" "$file"; then
    echo "FAIL: missing anchor '$anchor' in $file"
    fail=1
  fi
done

echo "Checking AGENTS.md for detailed role content (should live in docs/agents/)..."
if grep -nE '(^|\s)(Recommended model|Default model|Prompt template)(\s|:|$)' AGENTS.md; then
  echo "FAIL: AGENTS.md appears to contain model-selection or prompt-template content; move it to docs/agents/."
  fail=1
fi

echo "Checking documentarian sections..."
documentarian_sections=(
  "## Purpose"
  "## Use when"
  "## Do not use when"
  "## Inputs"
  "## Outputs"
  "## Allowed actions"
  "## Forbidden actions"
  "## Reads first"
  "## Return format"
  "## Escalation rules"
  "## Verification expectations"
)
for section in "${documentarian_sections[@]}"; do
  if ! grep -qF "$section" docs/agents/documentarian.md; then
    echo "FAIL: docs/agents/documentarian.md missing section: $section"
    fail=1
  fi
done

# Optional: when invoked with BASE_REF, warn if behavior-related files changed but no docs did.
if [ -n "${BASE_REF:-}" ]; then
  changed_src=$(git diff --name-only "$BASE_REF" -- 'src/**' 'demo/**' 'tools/**' 'fixtures/**' 2>/dev/null || true)
  changed_doc=$(git diff --name-only "$BASE_REF" -- \
    'AGENTS.md' 'README.md' 'testing.md' 'docs/**' 'INFRASTRUCTURE_SUMMARY.md' 'conductor/**' 2>/dev/null || true)
  if [ -n "$changed_src" ] && [ -z "$changed_doc" ]; then
    echo "WARN: code changes touched src/demo/tools/fixtures but no docs changed in this range. Consider invoking documentarian."
  fi
fi

if [ "$fail" -eq 0 ]; then
  echo "OK: agent-doc topology checks passed."
fi

exit "$fail"
